### ISSUE TITLE
Ownership

### ISSUE THREAD

**Issue by calvinmetcalf** [crypto-browserify/pbkdf2-compat#6]
@dcousens can you either publish version 3.0.0 or give me permission to? publicEncrypt and browserify-sign are waiting on this to be modularized

**Comment by dcousens** [comment]
@calvinmetcalf added you as a maintainer :), going to update/run https://github.com/crypto-browserify/ownership now to add everyone else.

Will publish `3.0.0` momentarily :)

**Comment by dcousens** [comment]
We need to merge #5, then we can go to `2.0.2`.  `3.0.0` shouldn't be necessary?

**Comment by calvinmetcalf** [comment]
we no longer have the inject functionality that crypto-browserify relied on so that's why it was a major version bump

**Comment by dcousens** [comment]
@calvinmetcalf oh true.  I guess `3.x.y` is fine then.

**Comment by dcousens** [comment]
@calvinmetcalf oh true.  I guess `3.x.y` is fine then.  Still needs #5 to be usable though.

**Comment by calvinmetcalf** [comment]
what do you mean about it not being usable now?
